In [38]:
import torch

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# inspiration from here https://discuss.pytorch.org/t/backpropagating-through-multiple-optimizer-steps/26017/2

model = nn.Linear(10, 2)


weights = torch.ones(10, requires_grad=True)
weights_test = torch.Tensor([-10,10,10,0,0,0,0,0,0,0])


criterion = nn.CrossEntropyLoss(reduction='none')
meta_opt = optim.Adam([weights])
opt  = optim.Adam(model.parameters())
target = torch.empty(10, dtype=torch.long).random_(2)

alpha = 0.001

x = torch.randn(10, 10)

for e in range(10000):
    # inner loop optimize the model weights
    meta_loss = 0
    
    for _ in range(1):
        model.zero_grad()
        output = model(x)
        loss = criterion(output, target)
        
        #print(loss)
        #print(torch.sum(loss * weights))
        w_loss = torch.sum(loss * weights)
        w_loss.backward()
     
        opt.step() # theta' = theta + f(weights)
        model.zero_grad()
      
        output = model(x) # y = model(theta', x)
        meta_loss_ = criterion(output,target)
        meta_loss += torch.sum(meta_loss_ * weights_test)
        
    print(meta_loss)
    meta_loss.backward()
    print(weights)

    meta_opt.step()


tensor(6.4850, grad_fn=<AddBackward0>)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)
tensor(6.4406, grad_fn=<AddBackward0>)
tensor([0.9990, 0.9990, 0.9990, 0.9990, 0.9990, 0.9990, 0.9990, 0.9990, 0.9990,
        0.9990], requires_grad=True)
tensor(6.3964, grad_fn=<AddBackward0>)
tensor([0.9980, 0.9980, 0.9980, 0.9980, 0.9980, 0.9980, 0.9980, 0.9980, 0.9980,
        0.9980], requires_grad=True)
tensor(6.3525, grad_fn=<AddBackward0>)
tensor([0.9971, 0.9971, 0.9971, 0.9971, 0.9971, 0.9971, 0.9971, 0.9971, 0.9971,
        0.9971], requires_grad=True)
tensor(6.3089, grad_fn=<AddBackward0>)
tensor([0.9961, 0.9961, 0.9961, 0.9961, 0.9961, 0.9961, 0.9961, 0.9961, 0.9961,
        0.9961], requires_grad=True)
tensor(6.2655, grad_fn=<AddBackward0>)
tensor([0.9951, 0.9952, 0.9951, 0.9951, 0.9951, 0.9952, 0.9951, 0.9951, 0.9951,
        0.9951], requires_grad=True)
tensor(6.2225, grad_fn=<AddBackward0>)
tensor([0.9942, 0.9942, 0.9942, 0.9942, 0.9942, 0.9942, 0.9942, 0.9942, 0

tensor([0.7781, 0.7670, 0.7812, 0.7710, 0.7696, 0.7623, 0.7714, 0.7725, 0.7706,
        0.7835], requires_grad=True)
tensor(2.8241, grad_fn=<AddBackward0>)
tensor([0.7767, 0.7654, 0.7798, 0.7694, 0.7680, 0.7606, 0.7698, 0.7710, 0.7690,
        0.7821], requires_grad=True)
tensor(2.8123, grad_fn=<AddBackward0>)
tensor([0.7752, 0.7638, 0.7784, 0.7679, 0.7664, 0.7590, 0.7683, 0.7694, 0.7675,
        0.7807], requires_grad=True)
tensor(2.8006, grad_fn=<AddBackward0>)
tensor([0.7738, 0.7622, 0.7769, 0.7664, 0.7648, 0.7573, 0.7667, 0.7679, 0.7659,
        0.7793], requires_grad=True)
tensor(2.7889, grad_fn=<AddBackward0>)
tensor([0.7723, 0.7606, 0.7755, 0.7648, 0.7633, 0.7557, 0.7652, 0.7663, 0.7644,
        0.7779], requires_grad=True)
tensor(2.7773, grad_fn=<AddBackward0>)
tensor([0.7709, 0.7590, 0.7741, 0.7633, 0.7617, 0.7540, 0.7636, 0.7648, 0.7628,
        0.7765], requires_grad=True)
tensor(2.7657, grad_fn=<AddBackward0>)
tensor([0.7694, 0.7574, 0.7727, 0.7617, 0.7601, 0.7523, 0.7621, 

tensor([0.6146, 0.5887, 0.6222, 0.5971, 0.5887, 0.5747, 0.5949, 0.5949, 0.5932,
        0.6253], requires_grad=True)
tensor(1.7843, grad_fn=<AddBackward0>)
tensor([0.6132, 0.5872, 0.6209, 0.5956, 0.5871, 0.5730, 0.5934, 0.5934, 0.5917,
        0.6239], requires_grad=True)
tensor(1.7776, grad_fn=<AddBackward0>)
tensor([0.6118, 0.5857, 0.6195, 0.5941, 0.5855, 0.5714, 0.5918, 0.5918, 0.5901,
        0.6225], requires_grad=True)
tensor(1.7710, grad_fn=<AddBackward0>)
tensor([0.6104, 0.5841, 0.6181, 0.5926, 0.5839, 0.5698, 0.5903, 0.5902, 0.5886,
        0.6212], requires_grad=True)
tensor(1.7644, grad_fn=<AddBackward0>)
tensor([0.6089, 0.5826, 0.6168, 0.5911, 0.5823, 0.5681, 0.5888, 0.5887, 0.5870,
        0.6198], requires_grad=True)
tensor(1.7578, grad_fn=<AddBackward0>)
tensor([0.6075, 0.5811, 0.6154, 0.5896, 0.5807, 0.5665, 0.5872, 0.5871, 0.5855,
        0.6184], requires_grad=True)
tensor(1.7513, grad_fn=<AddBackward0>)
tensor([0.6061, 0.5795, 0.6140, 0.5881, 0.5792, 0.5649, 0.5857, 

tensor([0.4339, 0.3941, 0.4475, 0.4060, 0.3836, 0.3655, 0.3968, 0.3935, 0.3932,
        0.4482], requires_grad=True)
tensor(1.1683, grad_fn=<AddBackward0>)
tensor([0.4325, 0.3926, 0.4462, 0.4046, 0.3821, 0.3639, 0.3952, 0.3920, 0.3917,
        0.4468], requires_grad=True)
tensor(1.1651, grad_fn=<AddBackward0>)
tensor([0.4312, 0.3911, 0.4449, 0.4031, 0.3805, 0.3624, 0.3937, 0.3904, 0.3902,
        0.4455], requires_grad=True)
tensor(1.1620, grad_fn=<AddBackward0>)
tensor([0.4298, 0.3897, 0.4436, 0.4017, 0.3789, 0.3608, 0.3922, 0.3889, 0.3886,
        0.4441], requires_grad=True)
tensor(1.1590, grad_fn=<AddBackward0>)
tensor([0.4284, 0.3882, 0.4423, 0.4003, 0.3774, 0.3592, 0.3907, 0.3874, 0.3871,
        0.4428], requires_grad=True)
tensor(1.1559, grad_fn=<AddBackward0>)
tensor([0.4271, 0.3867, 0.4409, 0.3988, 0.3758, 0.3576, 0.3892, 0.3858, 0.3856,
        0.4414], requires_grad=True)
tensor(1.1528, grad_fn=<AddBackward0>)
tensor([0.4257, 0.3853, 0.4396, 0.3974, 0.3742, 0.3560, 0.3877, 

tensor([0.2028, 0.1486, 0.2256, 0.1645, 0.1187, 0.0979, 0.1426, 0.1344, 0.1355,
        0.2198], requires_grad=True)
tensor(0.8861, grad_fn=<AddBackward0>)
tensor([0.2015, 0.1472, 0.2243, 0.1632, 0.1172, 0.0963, 0.1411, 0.1329, 0.1340,
        0.2184], requires_grad=True)
tensor(0.8859, grad_fn=<AddBackward0>)
tensor([0.2001, 0.1458, 0.2230, 0.1618, 0.1156, 0.0948, 0.1397, 0.1315, 0.1325,
        0.2171], requires_grad=True)
tensor(0.8857, grad_fn=<AddBackward0>)
tensor([0.1988, 0.1444, 0.2217, 0.1604, 0.1141, 0.0932, 0.1382, 0.1300, 0.1310,
        0.2158], requires_grad=True)
tensor(0.8855, grad_fn=<AddBackward0>)
tensor([0.1975, 0.1430, 0.2205, 0.1590, 0.1126, 0.0917, 0.1367, 0.1285, 0.1295,
        0.2145], requires_grad=True)
tensor(0.8853, grad_fn=<AddBackward0>)
tensor([0.1961, 0.1416, 0.2192, 0.1576, 0.1110, 0.0901, 0.1353, 0.1270, 0.1280,
        0.2132], requires_grad=True)
tensor(0.8852, grad_fn=<AddBackward0>)
tensor([0.1948, 0.1402, 0.2179, 0.1562, 0.1095, 0.0886, 0.1338, 

tensor([-0.0242, -0.0917,  0.0081, -0.0710, -0.1480, -0.1665, -0.1079, -0.1190,
        -0.1187, -0.0056], requires_grad=True)
tensor(1.4924, grad_fn=<AddBackward0>)
tensor([-0.0255, -0.0931,  0.0069, -0.0723, -0.1497, -0.1680, -0.1094, -0.1205,
        -0.1201, -0.0069], requires_grad=True)
tensor(1.4985, grad_fn=<AddBackward0>)
tensor([-0.0268, -0.0945,  0.0056, -0.0737, -0.1513, -0.1696, -0.1108, -0.1219,
        -0.1216, -0.0082], requires_grad=True)
tensor(1.5046, grad_fn=<AddBackward0>)
tensor([-0.0281, -0.0959,  0.0044, -0.0750, -0.1530, -0.1711, -0.1123, -0.1234,
        -0.1231, -0.0095], requires_grad=True)
tensor(1.5106, grad_fn=<AddBackward0>)
tensor([-0.0294, -0.0973,  0.0031, -0.0764, -0.1547, -0.1726, -0.1138, -0.1248,
        -0.1245, -0.0108], requires_grad=True)
tensor(1.5166, grad_fn=<AddBackward0>)
tensor([-0.0307, -0.0987,  0.0019, -0.0777, -0.1563, -0.1742, -0.1152, -0.1262,
        -0.1260, -0.0121], requires_grad=True)
tensor(1.5225, grad_fn=<AddBackward0>)
tens

tensor([-0.2368, -0.3226, -0.2024, -0.2934, -0.5169, -0.4232, -0.3659, -0.3502,
        -0.3713, -0.2272], requires_grad=True)
tensor(2.9856, grad_fn=<AddBackward0>)
tensor([-0.2380, -0.3240, -0.2037, -0.2947, -0.5197, -0.4248, -0.3677, -0.3516,
        -0.3730, -0.2287], requires_grad=True)
tensor(3.0183, grad_fn=<AddBackward0>)
tensor([-0.2393, -0.3253, -0.2050, -0.2960, -0.5226, -0.4263, -0.3694, -0.3529,
        -0.3747, -0.2301], requires_grad=True)
tensor(3.0518, grad_fn=<AddBackward0>)
tensor([-0.2405, -0.3267, -0.2062, -0.2973, -0.5254, -0.4278, -0.3712, -0.3542,
        -0.3764, -0.2315], requires_grad=True)
tensor(3.0859, grad_fn=<AddBackward0>)
tensor([-0.2417, -0.3280, -0.2075, -0.2986, -0.5282, -0.4294, -0.3729, -0.3555,
        -0.3781, -0.2330], requires_grad=True)
tensor(3.1208, grad_fn=<AddBackward0>)
tensor([-0.2430, -0.3294, -0.2088, -0.2999, -0.5310, -0.4309, -0.3747, -0.3568,
        -0.3798, -0.2344], requires_grad=True)
tensor(3.1563, grad_fn=<AddBackward0>)
tens

tensor(22.3109, grad_fn=<AddBackward0>)
tensor([-0.4449, -0.5443, -0.4537, -0.5058, -1.0167, -0.6817, -0.7255, -0.5661,
        -0.7350, -0.5798], requires_grad=True)
tensor(22.5060, grad_fn=<AddBackward0>)
tensor([-0.4461, -0.5456, -0.4555, -0.5070, -1.0196, -0.6832, -0.7280, -0.5673,
        -0.7376, -0.5826], requires_grad=True)
tensor(22.7015, grad_fn=<AddBackward0>)
tensor([-0.4473, -0.5468, -0.4573, -0.5082, -1.0225, -0.6848, -0.7304, -0.5685,
        -0.7401, -0.5854], requires_grad=True)
tensor(22.8976, grad_fn=<AddBackward0>)
tensor([-0.4485, -0.5481, -0.4592, -0.5094, -1.0254, -0.6863, -0.7329, -0.5697,
        -0.7427, -0.5883], requires_grad=True)
tensor(23.0941, grad_fn=<AddBackward0>)
tensor([-0.4498, -0.5494, -0.4610, -0.5106, -1.0283, -0.6878, -0.7353, -0.5710,
        -0.7452, -0.5911], requires_grad=True)
tensor(23.2912, grad_fn=<AddBackward0>)
tensor([-0.4510, -0.5506, -0.4629, -0.5118, -1.0312, -0.6893, -0.7378, -0.5722,
        -0.7478, -0.5939], requires_grad=True

tensor(57.0788, grad_fn=<AddBackward0>)
tensor([-0.6531, -0.7540, -0.8533, -0.7083, -1.4913, -0.9534, -1.1612, -0.7710,
        -1.1854, -1.0903], requires_grad=True)
tensor(57.2624, grad_fn=<AddBackward0>)
tensor([-0.6544, -0.7552, -0.8560, -0.7094, -1.4939, -0.9551, -1.1638, -0.7722,
        -1.1880, -1.0932], requires_grad=True)
tensor(57.4457, grad_fn=<AddBackward0>)
tensor([-0.6556, -0.7564, -0.8587, -0.7106, -1.4965, -0.9568, -1.1663, -0.7734,
        -1.1906, -1.0962], requires_grad=True)
tensor(57.6286, grad_fn=<AddBackward0>)
tensor([-0.6568, -0.7576, -0.8613, -0.7117, -1.4992, -0.9585, -1.1689, -0.7745,
        -1.1932, -1.0991], requires_grad=True)
tensor(57.8111, grad_fn=<AddBackward0>)
tensor([-0.6580, -0.7588, -0.8640, -0.7129, -1.5018, -0.9603, -1.1714, -0.7757,
        -1.1958, -1.1020], requires_grad=True)
tensor(57.9933, grad_fn=<AddBackward0>)
tensor([-0.6593, -0.7600, -0.8667, -0.7140, -1.5044, -0.9620, -1.1740, -0.7768,
        -1.1984, -1.1049], requires_grad=True

tensor(84.0869, grad_fn=<AddBackward0>)
tensor([-0.8652, -0.9509, -1.3057, -0.8995, -1.9148, -1.3009, -1.5839, -0.9641,
        -1.6105, -1.5604], requires_grad=True)
tensor(84.2304, grad_fn=<AddBackward0>)
tensor([-0.8665, -0.9521, -1.3083, -0.9006, -1.9172, -1.3033, -1.5864, -0.9652,
        -1.6129, -1.5631], requires_grad=True)
tensor(84.3738, grad_fn=<AddBackward0>)
tensor([-0.8678, -0.9532, -1.3110, -0.9017, -1.9196, -1.3058, -1.5888, -0.9663,
        -1.6154, -1.5657], requires_grad=True)
tensor(84.5170, grad_fn=<AddBackward0>)
tensor([-0.8691, -0.9544, -1.3136, -0.9028, -1.9220, -1.3082, -1.5912, -0.9674,
        -1.6178, -1.5684], requires_grad=True)
tensor(84.6601, grad_fn=<AddBackward0>)
tensor([-0.8704, -0.9555, -1.3162, -0.9040, -1.9244, -1.3106, -1.5937, -0.9685,
        -1.6202, -1.5710], requires_grad=True)
tensor(84.8031, grad_fn=<AddBackward0>)
tensor([-0.8717, -0.9567, -1.3188, -0.9051, -1.9268, -1.3131, -1.5961, -0.9697,
        -1.6226, -1.5736], requires_grad=True

tensor([-1.0963, -1.1415, -1.7297, -1.0845, -2.3041, -1.7376, -1.9823, -1.1504,
        -2.0044, -1.9841], requires_grad=True)
tensor(106.4511, grad_fn=<AddBackward0>)
tensor([-1.0977, -1.1426, -1.7322, -1.0856, -2.3063, -1.7402, -1.9846, -1.1515,
        -2.0066, -1.9865], requires_grad=True)
tensor(106.5724, grad_fn=<AddBackward0>)
tensor([-1.0992, -1.1437, -1.7346, -1.0867, -2.3086, -1.7429, -1.9869, -1.1526,
        -2.0089, -1.9889], requires_grad=True)
tensor(106.6936, grad_fn=<AddBackward0>)
tensor([-1.1007, -1.1448, -1.7370, -1.0878, -2.3108, -1.7456, -1.9892, -1.1537,
        -2.0112, -1.9913], requires_grad=True)
tensor(106.8147, grad_fn=<AddBackward0>)
tensor([-1.1022, -1.1460, -1.7394, -1.0889, -2.3131, -1.7482, -1.9915, -1.1548,
        -2.0134, -1.9937], requires_grad=True)
tensor(106.9356, grad_fn=<AddBackward0>)
tensor([-1.1036, -1.1471, -1.7419, -1.0899, -2.3153, -1.7509, -1.9938, -1.1559,
        -2.0157, -1.9961], requires_grad=True)
tensor(107.0564, grad_fn=<AddBack

tensor(124.9103, grad_fn=<AddBackward0>)
tensor([-1.3613, -1.3290, -2.1210, -1.2648, -2.6674, -2.1741, -2.3565, -1.3317,
        -2.3717, -2.3726], requires_grad=True)
tensor(125.0117, grad_fn=<AddBackward0>)
tensor([-1.3631, -1.3301, -2.1233, -1.2659, -2.6695, -2.1767, -2.3587, -1.3328,
        -2.3739, -2.3749], requires_grad=True)
tensor(125.1129, grad_fn=<AddBackward0>)
tensor([-1.3648, -1.3312, -2.1255, -1.2669, -2.6716, -2.1792, -2.3608, -1.3338,
        -2.3760, -2.3771], requires_grad=True)
tensor(125.2141, grad_fn=<AddBackward0>)
tensor([-1.3665, -1.3323, -2.1278, -1.2680, -2.6737, -2.1817, -2.3630, -1.3349,
        -2.3781, -2.3793], requires_grad=True)
tensor(125.3152, grad_fn=<AddBackward0>)
tensor([-1.3682, -1.3335, -2.1301, -1.2691, -2.6758, -2.1843, -2.3652, -1.3360,
        -2.3803, -2.3816], requires_grad=True)
tensor(125.4161, grad_fn=<AddBackward0>)
tensor([-1.3699, -1.3346, -2.1323, -1.2702, -2.6779, -2.1868, -2.3674, -1.3371,
        -2.3824, -2.3838], requires_gra

tensor([-1.6372, -1.4990, -2.4516, -1.4244, -2.9777, -2.5444, -2.6763, -1.4920,
        -2.6851, -2.7005], requires_grad=True)
tensor(139.0613, grad_fn=<AddBackward0>)
tensor([-1.6392, -1.5001, -2.4537, -1.4255, -2.9797, -2.5468, -2.6784, -1.4931,
        -2.6872, -2.7027], requires_grad=True)
tensor(139.1480, grad_fn=<AddBackward0>)
tensor([-1.6412, -1.5012, -2.4559, -1.4266, -2.9817, -2.5492, -2.6805, -1.4942,
        -2.6892, -2.7048], requires_grad=True)
tensor(139.2347, grad_fn=<AddBackward0>)
tensor([-1.6431, -1.5024, -2.4580, -1.4276, -2.9838, -2.5515, -2.6825, -1.4952,
        -2.6912, -2.7069], requires_grad=True)
tensor(139.3213, grad_fn=<AddBackward0>)
tensor([-1.6451, -1.5035, -2.4602, -1.4287, -2.9858, -2.5539, -2.6846, -1.4963,
        -2.6933, -2.7090], requires_grad=True)
tensor(139.4078, grad_fn=<AddBackward0>)
tensor([-1.6470, -1.5047, -2.4623, -1.4297, -2.9878, -2.5563, -2.6867, -1.4974,
        -2.6953, -2.7112], requires_grad=True)
tensor(139.4942, grad_fn=<AddBack

tensor([-1.9679, -1.6882, -2.7888, -1.5939, -3.2970, -2.9184, -3.0049, -1.6621,
        -3.0072, -3.0350], requires_grad=True)
tensor(152.1894, grad_fn=<AddBackward0>)
tensor([-1.9700, -1.6894, -2.7909, -1.5950, -3.2989, -2.9207, -3.0069, -1.6632,
        -3.0092, -3.0370], requires_grad=True)
tensor(152.2669, grad_fn=<AddBackward0>)
tensor([-1.9722, -1.6907, -2.7929, -1.5960, -3.3009, -2.9230, -3.0089, -1.6642,
        -3.0111, -3.0391], requires_grad=True)
tensor(152.3443, grad_fn=<AddBackward0>)
tensor([-1.9743, -1.6919, -2.7949, -1.5971, -3.3028, -2.9252, -3.0109, -1.6653,
        -3.0131, -3.0411], requires_grad=True)
tensor(152.4218, grad_fn=<AddBackward0>)
tensor([-1.9764, -1.6931, -2.7970, -1.5981, -3.3048, -2.9275, -3.0129, -1.6664,
        -3.0150, -3.0431], requires_grad=True)
tensor(152.4991, grad_fn=<AddBackward0>)
tensor([-1.9786, -1.6943, -2.7990, -1.5992, -3.3067, -2.9297, -3.0149, -1.6674,
        -3.0170, -3.0451], requires_grad=True)
tensor(152.5765, grad_fn=<AddBack

tensor([-2.3225, -1.8957, -3.1151, -1.7640, -3.6081, -3.2762, -3.3244, -1.8327,
        -3.3207, -3.3586], requires_grad=True)
tensor(164.5462, grad_fn=<AddBackward0>)
tensor([-2.3247, -1.8971, -3.1170, -1.7650, -3.6100, -3.2784, -3.3263, -1.8337,
        -3.3226, -3.3606], requires_grad=True)
tensor(164.6215, grad_fn=<AddBackward0>)
tensor([-2.3269, -1.8984, -3.1190, -1.7661, -3.6118, -3.2805, -3.3283, -1.8348,
        -3.3245, -3.3625], requires_grad=True)
tensor(164.6968, grad_fn=<AddBackward0>)
tensor([-2.3291, -1.8997, -3.1209, -1.7671, -3.6137, -3.2826, -3.3302, -1.8358,
        -3.3264, -3.3645], requires_grad=True)
tensor(164.7721, grad_fn=<AddBackward0>)
tensor([-2.3313, -1.9011, -3.1229, -1.7681, -3.6156, -3.2848, -3.3321, -1.8369,
        -3.3283, -3.3664], requires_grad=True)
tensor(164.8474, grad_fn=<AddBackward0>)
tensor([-2.3335, -1.9025, -3.1249, -1.7692, -3.6175, -3.2869, -3.3340, -1.8379,
        -3.3302, -3.3683], requires_grad=True)
tensor(164.9227, grad_fn=<AddBack

tensor([-2.6329, -2.0983, -3.3870, -1.9101, -3.8687, -3.5715, -3.5915, -1.9791,
        -3.5833, -3.6284], requires_grad=True)
tensor(175.3562, grad_fn=<AddBackward0>)
tensor([-2.6351, -2.0998, -3.3889, -1.9111, -3.8706, -3.5736, -3.5934, -1.9802,
        -3.5851, -3.6302], requires_grad=True)
tensor(175.4352, grad_fn=<AddBackward0>)
tensor([-2.6373, -2.1013, -3.3908, -1.9121, -3.8724, -3.5757, -3.5953, -1.9812,
        -3.5870, -3.6321], requires_grad=True)
tensor(175.5142, grad_fn=<AddBackward0>)
tensor([-2.6395, -2.1029, -3.3927, -1.9132, -3.8742, -3.5777, -3.5971, -1.9822,
        -3.5888, -3.6340], requires_grad=True)
tensor(175.5932, grad_fn=<AddBackward0>)
tensor([-2.6417, -2.1044, -3.3946, -1.9142, -3.8760, -3.5798, -3.5990, -1.9833,
        -3.5906, -3.6359], requires_grad=True)
tensor(175.6723, grad_fn=<AddBackward0>)
tensor([-2.6439, -2.1060, -3.3965, -1.9152, -3.8778, -3.5818, -3.6009, -1.9843,
        -3.5925, -3.6378], requires_grad=True)
tensor(175.7514, grad_fn=<AddBack

tensor(183.1714, grad_fn=<AddBackward0>)
tensor([-2.8446, -2.2557, -3.5692, -2.0101, -4.0440, -3.7682, -3.7709, -2.0794,
        -3.7598, -3.8091], requires_grad=True)
tensor(183.2557, grad_fn=<AddBackward0>)
tensor([-2.8468, -2.2575, -3.5711, -2.0111, -4.0458, -3.7702, -3.7727, -2.0804,
        -3.7616, -3.8110], requires_grad=True)
tensor(183.3400, grad_fn=<AddBackward0>)
tensor([-2.8490, -2.2592, -3.5729, -2.0122, -4.0476, -3.7722, -3.7745, -2.0815,
        -3.7634, -3.8128], requires_grad=True)
tensor(183.4244, grad_fn=<AddBackward0>)
tensor([-2.8511, -2.2609, -3.5748, -2.0132, -4.0494, -3.7742, -3.7764, -2.0825,
        -3.7652, -3.8147], requires_grad=True)
tensor(183.5089, grad_fn=<AddBackward0>)
tensor([-2.8533, -2.2626, -3.5767, -2.0142, -4.0512, -3.7762, -3.7782, -2.0835,
        -3.7670, -3.8165], requires_grad=True)
tensor(183.5934, grad_fn=<AddBackward0>)
tensor([-2.8555, -2.2643, -3.5785, -2.0152, -4.0530, -3.7782, -3.7800, -2.0846,
        -3.7688, -3.8183], requires_gra

tensor([-3.1494, -2.5191, -3.8297, -2.1560, -4.2953, -4.0478, -4.0275, -2.2256,
        -4.0127, -4.0675], requires_grad=True)
tensor(195.9333, grad_fn=<AddBackward0>)
tensor([-3.1515, -2.5211, -3.8315, -2.1570, -4.2970, -4.0497, -4.0293, -2.2266,
        -4.0145, -4.0693], requires_grad=True)
tensor(196.0276, grad_fn=<AddBackward0>)
tensor([-3.1536, -2.5231, -3.8333, -2.1580, -4.2988, -4.0517, -4.0311, -2.2276,
        -4.0162, -4.0711], requires_grad=True)
tensor(196.1221, grad_fn=<AddBackward0>)
tensor([-3.1558, -2.5251, -3.8351, -2.1591, -4.3005, -4.0536, -4.0329, -2.2286,
        -4.0180, -4.0728], requires_grad=True)
tensor(196.2166, grad_fn=<AddBackward0>)
tensor([-3.1579, -2.5271, -3.8369, -2.1601, -4.3023, -4.0556, -4.0347, -2.2297,
        -4.0197, -4.0746], requires_grad=True)
tensor(196.3112, grad_fn=<AddBackward0>)
tensor([-3.1600, -2.5291, -3.8387, -2.1611, -4.3040, -4.0575, -4.0365, -2.2307,
        -4.0215, -4.0764], requires_grad=True)
tensor(196.4058, grad_fn=<AddBack

tensor([-3.4406, -2.8135, -4.0781, -2.2982, -4.5357, -4.3132, -4.2727, -2.3680,
        -4.2546, -4.3139], requires_grad=True)
tensor(209.6161, grad_fn=<AddBackward0>)
tensor([-3.4427, -2.8157, -4.0799, -2.2993, -4.5374, -4.3150, -4.2744, -2.3691,
        -4.2563, -4.3156], requires_grad=True)
tensor(209.7180, grad_fn=<AddBackward0>)
tensor([-3.4447, -2.8179, -4.0817, -2.3003, -4.5391, -4.3169, -4.2761, -2.3701,
        -4.2581, -4.3174], requires_grad=True)
tensor(209.8198, grad_fn=<AddBackward0>)
tensor([-3.4468, -2.8202, -4.0834, -2.3013, -4.5408, -4.3188, -4.2779, -2.3711,
        -4.2598, -4.3191], requires_grad=True)
tensor(209.9216, grad_fn=<AddBackward0>)
tensor([-3.4489, -2.8224, -4.0852, -2.3023, -4.5425, -4.3207, -4.2796, -2.3721,
        -4.2615, -4.3209], requires_grad=True)
tensor(210.0235, grad_fn=<AddBackward0>)
tensor([-3.4510, -2.8246, -4.0869, -2.3034, -4.5442, -4.3226, -4.2814, -2.3731,
        -4.2632, -4.3226], requires_grad=True)
tensor(210.1254, grad_fn=<AddBack

tensor([-3.6638, -3.0623, -4.2689, -2.4095, -4.7207, -4.5161, -4.4610, -2.4794,
        -4.4408, -4.5030], requires_grad=True)
tensor(220.8585, grad_fn=<AddBackward0>)
tensor([-3.6659, -3.0646, -4.2706, -2.4105, -4.7224, -4.5180, -4.4627, -2.4804,
        -4.4425, -4.5047], requires_grad=True)
tensor(220.9625, grad_fn=<AddBackward0>)
tensor([-3.6679, -3.0669, -4.2724, -2.4115, -4.7241, -4.5198, -4.4644, -2.4814,
        -4.4442, -4.5064], requires_grad=True)
tensor(221.0666, grad_fn=<AddBackward0>)
tensor([-3.6699, -3.0693, -4.2741, -2.4125, -4.7257, -4.5217, -4.4662, -2.4825,
        -4.4459, -4.5082], requires_grad=True)
tensor(221.1706, grad_fn=<AddBackward0>)
tensor([-3.6719, -3.0716, -4.2758, -2.4135, -4.7274, -4.5235, -4.4679, -2.4835,
        -4.4476, -4.5099], requires_grad=True)
tensor(221.2747, grad_fn=<AddBackward0>)
tensor([-3.6740, -3.0739, -4.2776, -2.4146, -4.7291, -4.5253, -4.4696, -2.4845,
        -4.4493, -4.5116], requires_grad=True)
tensor(221.3787, grad_fn=<AddBack

tensor([-3.9796, -3.4340, -4.5398, -2.5703, -4.9839, -4.8032, -4.7286, -2.6404,
        -4.7056, -4.7715], requires_grad=True)
tensor(237.2751, grad_fn=<AddBackward0>)
tensor([-3.9816, -3.4363, -4.5415, -2.5713, -4.9856, -4.8050, -4.7303, -2.6414,
        -4.7073, -4.7731], requires_grad=True)
tensor(237.3783, grad_fn=<AddBackward0>)
tensor([-3.9835, -3.4387, -4.5431, -2.5723, -4.9872, -4.8068, -4.7319, -2.6424,
        -4.7089, -4.7748], requires_grad=True)
tensor(237.4815, grad_fn=<AddBackward0>)
tensor([-3.9855, -3.4411, -4.5448, -2.5733, -4.9889, -4.8086, -4.7336, -2.6434,
        -4.7106, -4.7765], requires_grad=True)
tensor(237.5846, grad_fn=<AddBackward0>)
tensor([-3.9875, -3.4434, -4.5465, -2.5743, -4.9905, -4.8104, -4.7353, -2.6445,
        -4.7122, -4.7782], requires_grad=True)
tensor(237.6878, grad_fn=<AddBackward0>)
tensor([-3.9894, -3.4458, -4.5482, -2.5753, -4.9922, -4.8122, -4.7370, -2.6455,
        -4.7139, -4.7799], requires_grad=True)
tensor(237.7909, grad_fn=<AddBack

tensor([-4.2809, -3.7964, -4.7996, -2.7276, -5.2370, -5.0774, -4.9853, -2.7979,
        -4.9602, -5.0289], requires_grad=True)
tensor(253.0598, grad_fn=<AddBackward0>)
tensor([-4.2828, -3.7987, -4.8013, -2.7286, -5.2386, -5.0792, -4.9870, -2.7989,
        -4.9618, -5.0305], requires_grad=True)
tensor(253.1601, grad_fn=<AddBackward0>)
tensor([-4.2847, -3.8011, -4.8029, -2.7296, -5.2402, -5.0809, -4.9886, -2.7999,
        -4.9634, -5.0322], requires_grad=True)
tensor(253.2604, grad_fn=<AddBackward0>)
tensor([-4.2866, -3.8034, -4.8046, -2.7306, -5.2418, -5.0827, -4.9902, -2.8009,
        -4.9650, -5.0338], requires_grad=True)
tensor(253.3606, grad_fn=<AddBackward0>)
tensor([-4.2885, -3.8057, -4.8062, -2.7316, -5.2435, -5.0844, -4.9919, -2.8019,
        -4.9667, -5.0354], requires_grad=True)
tensor(253.4609, grad_fn=<AddBackward0>)
tensor([-4.2904, -3.8080, -4.8079, -2.7326, -5.2451, -5.0862, -4.9935, -2.8029,
        -4.9683, -5.0371], requires_grad=True)
tensor(253.5611, grad_fn=<AddBack

tensor([-4.4692, -4.0227, -4.9628, -2.8279, -5.3962, -5.2491, -5.1466, -2.8982,
        -5.1203, -5.1905], requires_grad=True)
tensor(262.8811, grad_fn=<AddBackward0>)
tensor([-4.4710, -4.0250, -4.9645, -2.8289, -5.3977, -5.2508, -5.1482, -2.8992,
        -5.1219, -5.1921], requires_grad=True)
tensor(262.9792, grad_fn=<AddBackward0>)
tensor([-4.4729, -4.0272, -4.9661, -2.8299, -5.3993, -5.2525, -5.1498, -2.9003,
        -5.1235, -5.1937], requires_grad=True)
tensor(263.0773, grad_fn=<AddBackward0>)
tensor([-4.4748, -4.0295, -4.9677, -2.8309, -5.4009, -5.2542, -5.1514, -2.9013,
        -5.1251, -5.1953], requires_grad=True)
tensor(263.1753, grad_fn=<AddBackward0>)
tensor([-4.4767, -4.0317, -4.9694, -2.8319, -5.4025, -5.2559, -5.1530, -2.9023,
        -5.1267, -5.1970], requires_grad=True)
tensor(263.2733, grad_fn=<AddBackward0>)
tensor([-4.4786, -4.0340, -4.9710, -2.8329, -5.4041, -5.2577, -5.1547, -2.9033,
        -5.1283, -5.1986], requires_grad=True)
tensor(263.3713, grad_fn=<AddBack

tensor([-4.7690, -4.3795, -5.2241, -2.9907, -5.6512, -5.5228, -5.4046, -3.0612,
        -5.3768, -5.4490], requires_grad=True)
tensor(278.3834, grad_fn=<AddBackward0>)
tensor([-4.7709, -4.3817, -5.2257, -2.9917, -5.6528, -5.5245, -5.4062, -3.0622,
        -5.3784, -5.4506], requires_grad=True)
tensor(278.4778, grad_fn=<AddBackward0>)
tensor([-4.7727, -4.3839, -5.2273, -2.9927, -5.6543, -5.5262, -5.4078, -3.0632,
        -5.3800, -5.4522], requires_grad=True)
tensor(278.5723, grad_fn=<AddBackward0>)
tensor([-4.7746, -4.3860, -5.2289, -2.9937, -5.6559, -5.5278, -5.4094, -3.0642,
        -5.3816, -5.4538], requires_grad=True)
tensor(278.6667, grad_fn=<AddBackward0>)
tensor([-4.7764, -4.3882, -5.2305, -2.9947, -5.6575, -5.5295, -5.4109, -3.0652,
        -5.3831, -5.4554], requires_grad=True)
tensor(278.7611, grad_fn=<AddBackward0>)
tensor([-4.7782, -4.3904, -5.2321, -2.9957, -5.6590, -5.5312, -5.4125, -3.0662,
        -5.3847, -5.4570], requires_grad=True)
tensor(278.8555, grad_fn=<AddBack

tensor(289.7468, grad_fn=<AddBackward0>)
tensor([-4.9933, -4.6425, -5.4205, -3.1149, -5.8431, -5.7278, -5.5985, -3.1855,
        -5.5699, -5.6433], requires_grad=True)
tensor(289.8386, grad_fn=<AddBackward0>)
tensor([-4.9951, -4.6446, -5.4221, -3.1159, -5.8447, -5.7294, -5.6001, -3.1865,
        -5.5714, -5.6448], requires_grad=True)
tensor(289.9304, grad_fn=<AddBackward0>)
tensor([-4.9969, -4.6468, -5.4236, -3.1169, -5.8462, -5.7311, -5.6016, -3.1875,
        -5.5730, -5.6464], requires_grad=True)
tensor(290.0222, grad_fn=<AddBackward0>)
tensor([-4.9987, -4.6489, -5.4252, -3.1179, -5.8478, -5.7327, -5.6032, -3.1885,
        -5.5746, -5.6480], requires_grad=True)
tensor(290.1139, grad_fn=<AddBackward0>)
tensor([-5.0005, -4.6510, -5.4268, -3.1189, -5.8493, -5.7344, -5.6048, -3.1895,
        -5.5761, -5.6495], requires_grad=True)
tensor(290.2056, grad_fn=<AddBackward0>)
tensor([-5.0023, -4.6531, -5.4284, -3.1199, -5.8509, -5.7360, -5.6063, -3.1905,
        -5.5777, -5.6511], requires_gra

tensor([-5.2437, -4.9322, -5.6409, -3.2561, -6.0587, -5.9570, -5.8160, -3.3267,
        -5.7868, -5.8612], requires_grad=True)
tensor(302.4842, grad_fn=<AddBackward0>)
tensor([-5.2455, -4.9343, -5.6425, -3.2571, -6.0602, -5.9586, -5.8176, -3.3277,
        -5.7883, -5.8627], requires_grad=True)
tensor(302.5731, grad_fn=<AddBackward0>)
tensor([-5.2473, -4.9363, -5.6440, -3.2581, -6.0617, -5.9602, -5.8191, -3.3287,
        -5.7899, -5.8643], requires_grad=True)
tensor(302.6620, grad_fn=<AddBackward0>)
tensor([-5.2490, -4.9383, -5.6456, -3.2591, -6.0633, -5.9618, -5.8206, -3.3298,
        -5.7914, -5.8658], requires_grad=True)
tensor(302.7508, grad_fn=<AddBackward0>)
tensor([-5.2508, -4.9404, -5.6472, -3.2601, -6.0648, -5.9635, -5.8222, -3.3308,
        -5.7930, -5.8674], requires_grad=True)
tensor(302.8396, grad_fn=<AddBackward0>)
tensor([-5.2526, -4.9424, -5.6487, -3.2611, -6.0663, -5.9651, -5.8237, -3.3318,
        -5.7945, -5.8689], requires_grad=True)
tensor(302.9283, grad_fn=<AddBack

tensor([-5.4582, -5.1769, -5.8305, -3.3790, -6.2442, -6.1534, -6.0030, -3.4497,
        -5.9735, -6.0485], requires_grad=True)
tensor(313.1779, grad_fn=<AddBackward0>)
tensor([-5.4599, -5.1789, -5.8321, -3.3800, -6.2457, -6.1550, -6.0045, -3.4507,
        -5.9751, -6.0500], requires_grad=True)
tensor(313.2643, grad_fn=<AddBackward0>)
tensor([-5.4617, -5.1808, -5.8336, -3.3810, -6.2472, -6.1566, -6.0061, -3.4517,
        -5.9766, -6.0516], requires_grad=True)
tensor(313.3507, grad_fn=<AddBackward0>)
tensor([-5.4634, -5.1828, -5.8352, -3.3820, -6.2488, -6.1582, -6.0076, -3.4527,
        -5.9781, -6.0531], requires_grad=True)
tensor(313.4371, grad_fn=<AddBackward0>)
tensor([-5.4652, -5.1848, -5.8367, -3.3830, -6.2503, -6.1598, -6.0091, -3.4537,
        -5.9796, -6.0546], requires_grad=True)
tensor(313.5235, grad_fn=<AddBackward0>)
tensor([-5.4669, -5.1868, -5.8383, -3.3840, -6.2518, -6.1614, -6.0106, -3.4547,
        -5.9811, -6.0561], requires_grad=True)
tensor(313.6099, grad_fn=<AddBack

tensor(325.9305, grad_fn=<AddBackward0>)
tensor([-5.7192, -5.4706, -6.0622, -3.5310, -6.4711, -6.3926, -6.2314, -3.6017,
        -6.2019, -6.2773], requires_grad=True)
tensor(326.0141, grad_fn=<AddBackward0>)
tensor([-5.7209, -5.4725, -6.0638, -3.5320, -6.4726, -6.3942, -6.2329, -3.6027,
        -6.2034, -6.2788], requires_grad=True)
tensor(326.0977, grad_fn=<AddBackward0>)
tensor([-5.7226, -5.4744, -6.0653, -3.5330, -6.4741, -6.3957, -6.2344, -3.6038,
        -6.2049, -6.2804], requires_grad=True)
tensor(326.1812, grad_fn=<AddBackward0>)
tensor([-5.7243, -5.4763, -6.0668, -3.5340, -6.4755, -6.3973, -6.2359, -3.6048,
        -6.2064, -6.2819], requires_grad=True)
tensor(326.2648, grad_fn=<AddBackward0>)
tensor([-5.7260, -5.4782, -6.0683, -3.5350, -6.4770, -6.3989, -6.2374, -3.6058,
        -6.2079, -6.2834], requires_grad=True)
tensor(326.3484, grad_fn=<AddBackward0>)
tensor([-5.7277, -5.4802, -6.0699, -3.5360, -6.4785, -6.4004, -6.2389, -3.6068,
        -6.2094, -6.2849], requires_gra

tensor(338.2721, grad_fn=<AddBackward0>)
tensor([-5.9740, -5.7534, -6.2894, -3.6818, -6.6936, -6.6262, -6.4551, -3.7526,
        -6.4260, -6.5015], requires_grad=True)
tensor(338.3530, grad_fn=<AddBackward0>)
tensor([-5.9756, -5.7552, -6.2909, -3.6828, -6.6950, -6.6277, -6.4566, -3.7536,
        -6.4275, -6.5030], requires_grad=True)
tensor(338.4340, grad_fn=<AddBackward0>)
tensor([-5.9773, -5.7571, -6.2924, -3.6838, -6.6965, -6.6293, -6.4580, -3.7546,
        -6.4290, -6.5045], requires_grad=True)
tensor(338.5149, grad_fn=<AddBackward0>)
tensor([-5.9790, -5.7590, -6.2940, -3.6848, -6.6980, -6.6308, -6.4595, -3.7556,
        -6.4304, -6.5060], requires_grad=True)
tensor(338.5959, grad_fn=<AddBackward0>)
tensor([-5.9807, -5.7608, -6.2955, -3.6858, -6.6995, -6.6323, -6.4610, -3.7566,
        -6.4319, -6.5075], requires_grad=True)
tensor(338.6767, grad_fn=<AddBackward0>)
tensor([-5.9824, -5.7627, -6.2970, -3.6868, -6.7009, -6.6339, -6.4625, -3.7576,
        -6.4334, -6.5090], requires_gra

tensor([-6.2313, -6.0355, -6.5198, -3.8365, -6.9192, -6.8621, -6.6817, -3.9074,
        -6.6534, -6.7287], requires_grad=True)
tensor(350.6254, grad_fn=<AddBackward0>)
tensor([-6.2330, -6.0373, -6.5213, -3.8375, -6.9207, -6.8636, -6.6832, -3.9084,
        -6.6548, -6.7302], requires_grad=True)
tensor(350.7039, grad_fn=<AddBackward0>)
tensor([-6.2346, -6.0391, -6.5228, -3.8385, -6.9221, -6.8651, -6.6846, -3.9094,
        -6.6563, -6.7317], requires_grad=True)
tensor(350.7823, grad_fn=<AddBackward0>)
tensor([-6.2363, -6.0409, -6.5243, -3.8395, -6.9236, -6.8666, -6.6861, -3.9104,
        -6.6578, -6.7331], requires_grad=True)
tensor(350.8607, grad_fn=<AddBackward0>)
tensor([-6.2380, -6.0427, -6.5258, -3.8405, -6.9251, -6.8682, -6.6876, -3.9114,
        -6.6592, -6.7346], requires_grad=True)
tensor(350.9392, grad_fn=<AddBackward0>)
tensor([-6.2396, -6.0445, -6.5272, -3.8415, -6.9265, -6.8697, -6.6890, -3.9124,
        -6.6607, -6.7361], requires_grad=True)
tensor(351.0176, grad_fn=<AddBack

tensor([-6.4946, -6.3207, -6.7563, -3.9972, -7.1510, -7.1033, -6.9141, -4.0681,
        -6.8870, -6.9618], requires_grad=True)
tensor(362.9941, grad_fn=<AddBackward0>)
tensor([-6.4963, -6.3224, -6.7578, -3.9982, -7.1524, -7.1048, -6.9156, -4.0691,
        -6.8884, -6.9633], requires_grad=True)
tensor(363.0702, grad_fn=<AddBackward0>)
tensor([-6.4979, -6.3242, -6.7593, -3.9992, -7.1538, -7.1063, -6.9170, -4.0701,
        -6.8899, -6.9647], requires_grad=True)
tensor(363.1464, grad_fn=<AddBackward0>)
tensor([-6.4995, -6.3259, -6.7607, -4.0002, -7.1553, -7.1078, -6.9185, -4.0711,
        -6.8913, -6.9662], requires_grad=True)
tensor(363.2226, grad_fn=<AddBackward0>)
tensor([-6.5012, -6.3277, -6.7622, -4.0012, -7.1567, -7.1093, -6.9199, -4.0721,
        -6.8928, -6.9676], requires_grad=True)
tensor(363.2986, grad_fn=<AddBackward0>)
tensor([-6.5028, -6.3295, -6.7637, -4.0022, -7.1581, -7.1108, -6.9214, -4.0731,
        -6.8942, -6.9691], requires_grad=True)
tensor(363.3748, grad_fn=<AddBack

tensor([-6.7606, -6.6056, -6.9960, -4.1617, -7.3858, -7.3468, -7.1494, -4.2327,
        -7.1238, -7.1978], requires_grad=True)
tensor(375.3210, grad_fn=<AddBackward0>)
tensor([-6.7622, -6.6073, -6.9974, -4.1627, -7.3872, -7.3483, -7.1508, -4.2337,
        -7.1252, -7.1993], requires_grad=True)
tensor(375.3952, grad_fn=<AddBackward0>)
tensor([-6.7638, -6.6090, -6.9989, -4.1637, -7.3886, -7.3498, -7.1522, -4.2347,
        -7.1267, -7.2007], requires_grad=True)
tensor(375.4695, grad_fn=<AddBackward0>)
tensor([-6.7654, -6.6107, -7.0003, -4.1647, -7.3900, -7.3513, -7.1536, -4.2357,
        -7.1281, -7.2021], requires_grad=True)
tensor(375.5436, grad_fn=<AddBackward0>)
tensor([-6.7670, -6.6124, -7.0018, -4.1657, -7.3914, -7.3527, -7.1551, -4.2367,
        -7.1295, -7.2036], requires_grad=True)
tensor(375.6178, grad_fn=<AddBackward0>)
tensor([-6.7686, -6.6141, -7.0032, -4.1667, -7.3929, -7.3542, -7.1565, -4.2377,
        -7.1310, -7.2050], requires_grad=True)
tensor(375.6919, grad_fn=<AddBack

tensor(387.2774, grad_fn=<AddBackward0>)
tensor([-7.0228, -6.8838, -7.2330, -4.3262, -7.6180, -7.5868, -7.3818, -4.3972,
        -7.3582, -7.4311], requires_grad=True)
tensor(387.3500, grad_fn=<AddBackward0>)
tensor([-7.0244, -6.8855, -7.2344, -4.3272, -7.6194, -7.5882, -7.3832, -4.3982,
        -7.3596, -7.4325], requires_grad=True)
tensor(387.4225, grad_fn=<AddBackward0>)
tensor([-7.0260, -6.8871, -7.2359, -4.3282, -7.6208, -7.5897, -7.3846, -4.3992,
        -7.3610, -7.4339], requires_grad=True)
tensor(387.4951, grad_fn=<AddBackward0>)
tensor([-7.0276, -6.8888, -7.2373, -4.3292, -7.6222, -7.5912, -7.3860, -4.4002,
        -7.3624, -7.4353], requires_grad=True)
tensor(387.5676, grad_fn=<AddBackward0>)
tensor([-7.0291, -6.8905, -7.2387, -4.3302, -7.6236, -7.5926, -7.3874, -4.4012,
        -7.3639, -7.4367], requires_grad=True)
tensor(387.6401, grad_fn=<AddBackward0>)
tensor([-7.0307, -6.8922, -7.2402, -4.3312, -7.6250, -7.5941, -7.3888, -4.4022,
        -7.3653, -7.4382], requires_gra

tensor([-7.2706, -7.1445, -7.4576, -4.4836, -7.8381, -7.8134, -7.6017, -4.5546,
        -7.5804, -7.6520], requires_grad=True)
tensor(398.6359, grad_fn=<AddBackward0>)
tensor([-7.2722, -7.1461, -7.4590, -4.4846, -7.8395, -7.8149, -7.6031, -4.5556,
        -7.5818, -7.6534], requires_grad=True)
tensor(398.7072, grad_fn=<AddBackward0>)
tensor([-7.2738, -7.1478, -7.4605, -4.4856, -7.8409, -7.8163, -7.6045, -4.5566,
        -7.5833, -7.6548], requires_grad=True)
tensor(398.7784, grad_fn=<AddBackward0>)
tensor([-7.2753, -7.1494, -7.4619, -4.4866, -7.8423, -7.8177, -7.6059, -4.5576,
        -7.5847, -7.6562], requires_grad=True)
tensor(398.8498, grad_fn=<AddBackward0>)
tensor([-7.2769, -7.1510, -7.4633, -4.4876, -7.8437, -7.8192, -7.6073, -4.5586,
        -7.5861, -7.6576], requires_grad=True)
tensor(398.9210, grad_fn=<AddBackward0>)
tensor([-7.2785, -7.1527, -7.4647, -4.4886, -7.8451, -7.8206, -7.6087, -4.5596,
        -7.5875, -7.6590], requires_grad=True)
tensor(398.9922, grad_fn=<AddBack

tensor([-7.5016, -7.3856, -7.6674, -4.6319, -8.0437, -8.0245, -7.8070, -4.7029,
        -7.7882, -7.8582], requires_grad=True)
tensor(409.1067, grad_fn=<AddBackward0>)
tensor([-7.5031, -7.3873, -7.6689, -4.6329, -8.0451, -8.0259, -7.8084, -4.7039,
        -7.7896, -7.8596], requires_grad=True)
tensor(409.1769, grad_fn=<AddBackward0>)
tensor([-7.5047, -7.3889, -7.6703, -4.6339, -8.0464, -8.0273, -7.8098, -4.7049,
        -7.7910, -7.8610], requires_grad=True)
tensor(409.2472, grad_fn=<AddBackward0>)
tensor([-7.5062, -7.3905, -7.6717, -4.6349, -8.0478, -8.0287, -7.8112, -4.7059,
        -7.7924, -7.8624], requires_grad=True)
tensor(409.3174, grad_fn=<AddBackward0>)
tensor([-7.5078, -7.3921, -7.6731, -4.6359, -8.0492, -8.0301, -7.8126, -4.7069,
        -7.7937, -7.8638], requires_grad=True)
tensor(409.3877, grad_fn=<AddBackward0>)
tensor([-7.5093, -7.3937, -7.6745, -4.6369, -8.0506, -8.0316, -7.8139, -4.7079,
        -7.7951, -7.8652], requires_grad=True)
tensor(409.4579, grad_fn=<AddBack

tensor(419.5807, grad_fn=<AddBackward0>)
tensor([-7.7346, -7.6275, -7.8797, -4.7832, -8.2517, -8.2374, -8.0146, -4.8542,
        -7.9984, -8.0667], requires_grad=True)
tensor(419.6502, grad_fn=<AddBackward0>)
tensor([-7.7361, -7.6291, -7.8811, -4.7842, -8.2530, -8.2388, -8.0159, -4.8552,
        -7.9998, -8.0681], requires_grad=True)
tensor(419.7196, grad_fn=<AddBackward0>)
tensor([-7.7377, -7.6307, -7.8825, -4.7852, -8.2544, -8.2402, -8.0173, -4.8562,
        -8.0012, -8.0695], requires_grad=True)
tensor(419.7890, grad_fn=<AddBackward0>)
tensor([-7.7392, -7.6323, -7.8839, -4.7862, -8.2558, -8.2416, -8.0187, -4.8572,
        -8.0026, -8.0709], requires_grad=True)
tensor(419.8584, grad_fn=<AddBackward0>)
tensor([-7.7407, -7.6339, -7.8853, -4.7872, -8.2572, -8.2430, -8.0200, -4.8582,
        -8.0040, -8.0722], requires_grad=True)
tensor(419.9277, grad_fn=<AddBackward0>)
tensor([-7.7423, -7.6355, -7.8867, -4.7882, -8.2585, -8.2444, -8.0214, -4.8592,
        -8.0053, -8.0736], requires_gra

tensor([-7.9636, -7.8639, -8.0889, -4.9334, -8.4566, -8.4467, -8.2188, -5.0045,
        -8.2057, -8.2721], requires_grad=True)
tensor(430.0067, grad_fn=<AddBackward0>)
tensor([-7.9652, -7.8655, -8.0903, -4.9344, -8.4580, -8.4481, -8.2202, -5.0055,
        -8.2070, -8.2735], requires_grad=True)
tensor(430.0753, grad_fn=<AddBackward0>)
tensor([-7.9667, -7.8671, -8.0917, -4.9354, -8.4593, -8.4495, -8.2216, -5.0065,
        -8.2084, -8.2748], requires_grad=True)
tensor(430.1440, grad_fn=<AddBackward0>)
tensor([-7.9682, -7.8686, -8.0931, -4.9364, -8.4607, -8.4508, -8.2229, -5.0075,
        -8.2098, -8.2762], requires_grad=True)
tensor(430.2126, grad_fn=<AddBackward0>)
tensor([-7.9697, -7.8702, -8.0945, -4.9374, -8.4620, -8.4522, -8.2243, -5.0085,
        -8.2112, -8.2776], requires_grad=True)
tensor(430.2813, grad_fn=<AddBackward0>)
tensor([-7.9712, -7.8718, -8.0959, -4.9384, -8.4634, -8.4536, -8.2256, -5.0095,
        -8.2125, -8.2789], requires_grad=True)
tensor(430.3500, grad_fn=<AddBack

tensor(439.5837, grad_fn=<AddBackward0>)
tensor([-8.1768, -8.0829, -8.2841, -5.0746, -8.6478, -8.6415, -8.4093, -5.1457,
        -8.3991, -8.4637], requires_grad=True)
tensor(439.6519, grad_fn=<AddBackward0>)
tensor([-8.1783, -8.0845, -8.2854, -5.0756, -8.6491, -8.6429, -8.4107, -5.1467,
        -8.4005, -8.4650], requires_grad=True)
tensor(439.7199, grad_fn=<AddBackward0>)
tensor([-8.1798, -8.0860, -8.2868, -5.0766, -8.6505, -8.6442, -8.4120, -5.1477,
        -8.4018, -8.4664], requires_grad=True)
tensor(439.7881, grad_fn=<AddBackward0>)
tensor([-8.1813, -8.0876, -8.2882, -5.0776, -8.6519, -8.6456, -8.4133, -5.1487,
        -8.4032, -8.4677], requires_grad=True)
tensor(439.8562, grad_fn=<AddBackward0>)
tensor([-8.1828, -8.0891, -8.2896, -5.0786, -8.6532, -8.6470, -8.4147, -5.1497,
        -8.4046, -8.4691], requires_grad=True)
tensor(439.9243, grad_fn=<AddBackward0>)
tensor([-8.1843, -8.0906, -8.2910, -5.0796, -8.6546, -8.6484, -8.4160, -5.1507,
        -8.4059, -8.4704], requires_gra

tensor([-8.3656, -8.2762, -8.4573, -5.2007, -8.8175, -8.8141, -8.5783, -5.2718,
        -8.5709, -8.6336], requires_grad=True)
tensor(448.2059, grad_fn=<AddBackward0>)
tensor([-8.3671, -8.2777, -8.4587, -5.2017, -8.8189, -8.8155, -8.5796, -5.2728,
        -8.5722, -8.6350], requires_grad=True)
tensor(448.2736, grad_fn=<AddBackward0>)
tensor([-8.3686, -8.2792, -8.4601, -5.2027, -8.8202, -8.8168, -8.5810, -5.2738,
        -8.5736, -8.6363], requires_grad=True)
tensor(448.3412, grad_fn=<AddBackward0>)
tensor([-8.3701, -8.2807, -8.4614, -5.2037, -8.8216, -8.8182, -8.5823, -5.2748,
        -8.5749, -8.6377], requires_grad=True)
tensor(448.4089, grad_fn=<AddBackward0>)
tensor([-8.3716, -8.2823, -8.4628, -5.2047, -8.8229, -8.8196, -8.5836, -5.2758,
        -8.5763, -8.6390], requires_grad=True)
tensor(448.4765, grad_fn=<AddBackward0>)
tensor([-8.3731, -8.2838, -8.4642, -5.2057, -8.8243, -8.8209, -8.5850, -5.2768,
        -8.5777, -8.6404], requires_grad=True)
tensor(448.5443, grad_fn=<AddBack

tensor(459.1255, grad_fn=<AddBackward0>)
tensor([-8.6076, -8.5229, -8.6799, -5.3639, -9.0356, -9.0355, -8.7953, -5.4350,
        -8.7916, -8.8520], requires_grad=True)
tensor(459.1927, grad_fn=<AddBackward0>)
tensor([-8.6090, -8.5244, -8.6813, -5.3649, -9.0370, -9.0368, -8.7966, -5.4360,
        -8.7930, -8.8533], requires_grad=True)
tensor(459.2598, grad_fn=<AddBackward0>)
tensor([-8.6105, -8.5259, -8.6826, -5.3659, -9.0383, -9.0382, -8.7979, -5.4370,
        -8.7943, -8.8546], requires_grad=True)
tensor(459.3269, grad_fn=<AddBackward0>)
tensor([-8.6120, -8.5274, -8.6840, -5.3669, -9.0396, -9.0395, -8.7993, -5.4380,
        -8.7957, -8.8560], requires_grad=True)
tensor(459.3941, grad_fn=<AddBackward0>)
tensor([-8.6135, -8.5289, -8.6853, -5.3679, -9.0410, -9.0409, -8.8006, -5.4390,
        -8.7970, -8.8573], requires_grad=True)
tensor(459.4612, grad_fn=<AddBackward0>)
tensor([-8.6149, -8.5304, -8.6867, -5.3689, -9.0423, -9.0422, -8.8019, -5.4400,
        -8.7984, -8.8586], requires_gra

tensor(469.9665, grad_fn=<AddBackward0>)
tensor([-8.8456, -8.7647, -8.8995, -5.5260, -9.2508, -9.2534, -9.0092, -5.5971,
        -9.0095, -9.0673], requires_grad=True)
tensor(470.0333, grad_fn=<AddBackward0>)
tensor([-8.8470, -8.7662, -8.9008, -5.5270, -9.2521, -9.2548, -9.0106, -5.5981,
        -9.0109, -9.0686], requires_grad=True)
tensor(470.0999, grad_fn=<AddBackward0>)
tensor([-8.8485, -8.7677, -8.9022, -5.5280, -9.2535, -9.2561, -9.0119, -5.5991,
        -9.0122, -9.0700], requires_grad=True)
tensor(470.1666, grad_fn=<AddBackward0>)
tensor([-8.8500, -8.7692, -8.9035, -5.5290, -9.2548, -9.2575, -9.0132, -5.6001,
        -9.0135, -9.0713], requires_grad=True)
tensor(470.2333, grad_fn=<AddBackward0>)
tensor([-8.8514, -8.7707, -8.9049, -5.5300, -9.2561, -9.2588, -9.0145, -5.6011,
        -9.0149, -9.0726], requires_grad=True)
tensor(470.3000, grad_fn=<AddBackward0>)
tensor([-8.8529, -8.7722, -8.9062, -5.5310, -9.2574, -9.2601, -9.0158, -5.6021,
        -9.0162, -9.0739], requires_gra

        -9.2126, -9.2679], requires_grad=True)
tensor(480.1414, grad_fn=<AddBackward0>)
tensor([-9.0682, -8.9903, -9.1054, -5.6792, -9.4527, -9.4576, -9.2099, -5.7503,
        -9.2140, -9.2693], requires_grad=True)
tensor(480.2077, grad_fn=<AddBackward0>)
tensor([-9.0697, -8.9918, -9.1068, -5.6802, -9.4540, -9.4589, -9.2112, -5.7513,
        -9.2153, -9.2706], requires_grad=True)
tensor(480.2741, grad_fn=<AddBackward0>)
tensor([-9.0711, -8.9932, -9.1081, -5.6812, -9.4553, -9.4602, -9.2125, -5.7523,
        -9.2166, -9.2719], requires_grad=True)
tensor(480.3403, grad_fn=<AddBackward0>)
tensor([-9.0726, -8.9947, -9.1095, -5.6822, -9.4566, -9.4616, -9.2138, -5.7533,
        -9.2179, -9.2732], requires_grad=True)
tensor(480.4067, grad_fn=<AddBackward0>)
tensor([-9.0740, -8.9962, -9.1108, -5.6832, -9.4579, -9.4629, -9.2151, -5.7543,
        -9.2193, -9.2745], requires_grad=True)
tensor(480.4730, grad_fn=<AddBackward0>)
tensor([-9.0755, -8.9976, -9.1121, -5.6842, -9.4592, -9.4642, -9.2164, -

tensor(489.6009, grad_fn=<AddBackward0>)
tensor([-9.2745, -9.1988, -9.2967, -5.8222, -9.6402, -9.6469, -9.3962, -5.8934,
        -9.4039, -9.4568], requires_grad=True)
tensor(489.6668, grad_fn=<AddBackward0>)
tensor([-9.2759, -9.2002, -9.2981, -5.8232, -9.6415, -9.6483, -9.3975, -5.8944,
        -9.4052, -9.4581], requires_grad=True)
tensor(489.7329, grad_fn=<AddBackward0>)
tensor([-9.2774, -9.2017, -9.2994, -5.8242, -9.6428, -9.6496, -9.3988, -5.8954,
        -9.4065, -9.4594], requires_grad=True)
tensor(489.7988, grad_fn=<AddBackward0>)
tensor([-9.2788, -9.2031, -9.3007, -5.8252, -9.6441, -9.6509, -9.4001, -5.8964,
        -9.4079, -9.4608], requires_grad=True)
tensor(489.8648, grad_fn=<AddBackward0>)
tensor([-9.2803, -9.2046, -9.3021, -5.8262, -9.6454, -9.6522, -9.4014, -5.8974,
        -9.4092, -9.4621], requires_grad=True)
tensor(489.9309, grad_fn=<AddBackward0>)
tensor([-9.2817, -9.2060, -9.3034, -5.8272, -9.6467, -9.6535, -9.4027, -5.8984,
        -9.4105, -9.4634], requires_gra

tensor([-9.4919, -9.4180, -9.4988, -5.9743, -9.8384, -9.8468, -9.5930, -6.0454,
        -9.6046, -9.6550], requires_grad=True)
tensor(499.6727, grad_fn=<AddBackward0>)
tensor([-9.4934, -9.4195, -9.5002, -5.9753, -9.8397, -9.8481, -9.5943, -6.0464,
        -9.6059, -9.6563], requires_grad=True)
tensor(499.7384, grad_fn=<AddBackward0>)
tensor([-9.4948, -9.4209, -9.5015, -5.9763, -9.8410, -9.8494, -9.5956, -6.0474,
        -9.6073, -9.6576], requires_grad=True)
tensor(499.8041, grad_fn=<AddBackward0>)
tensor([-9.4962, -9.4223, -9.5028, -5.9773, -9.8423, -9.8507, -9.5968, -6.0484,
        -9.6086, -9.6589], requires_grad=True)
tensor(499.8698, grad_fn=<AddBackward0>)
tensor([-9.4976, -9.4238, -9.5041, -5.9783, -9.8436, -9.8520, -9.5981, -6.0494,
        -9.6099, -9.6602], requires_grad=True)
tensor(499.9354, grad_fn=<AddBackward0>)
tensor([-9.4990, -9.4252, -9.5055, -5.9793, -9.8449, -9.8533, -9.5994, -6.0504,
        -9.6112, -9.6615], requires_grad=True)
tensor(500.0011, grad_fn=<AddBack

tensor(509.5668, grad_fn=<AddBackward0>)
tensor([ -9.7075,  -9.6350,  -9.6998,  -6.1264, -10.0354, -10.0452,  -9.7886,
         -6.1975,  -9.8042,  -9.8520], requires_grad=True)
tensor(509.6322, grad_fn=<AddBackward0>)
tensor([ -9.7089,  -9.6364,  -9.7011,  -6.1274, -10.0367, -10.0465,  -9.7899,
         -6.1985,  -9.8055,  -9.8533], requires_grad=True)
tensor(509.6976, grad_fn=<AddBackward0>)
tensor([ -9.7103,  -9.6379,  -9.7024,  -6.1284, -10.0380, -10.0478,  -9.7912,
         -6.1995,  -9.8069,  -9.8546], requires_grad=True)
tensor(509.7629, grad_fn=<AddBackward0>)
tensor([ -9.7117,  -9.6393,  -9.7037,  -6.1294, -10.0393, -10.0492,  -9.7925,
         -6.2005,  -9.8082,  -9.8559], requires_grad=True)
tensor(509.8283, grad_fn=<AddBackward0>)
tensor([ -9.7132,  -9.6407,  -9.7050,  -6.1304, -10.0406, -10.0505,  -9.7937,
         -6.2015,  -9.8095,  -9.8572], requires_grad=True)
tensor(509.8937, grad_fn=<AddBackward0>)
tensor([ -9.7146,  -9.6421,  -9.7063,  -6.1314, -10.0419, -10.0518,  

tensor([ -9.8765,  -9.8048,  -9.8576,  -6.2464, -10.1902, -10.2010,  -9.9423,
         -6.3176,  -9.9611, -10.0068], requires_grad=True)
tensor(517.4652, grad_fn=<AddBackward0>)
tensor([ -9.8779,  -9.8062,  -9.8589,  -6.2474, -10.1915, -10.2023,  -9.9435,
         -6.3186,  -9.9624, -10.0081], requires_grad=True)
tensor(517.5304, grad_fn=<AddBackward0>)
tensor([ -9.8793,  -9.8077,  -9.8602,  -6.2484, -10.1928, -10.2036,  -9.9448,
         -6.3196,  -9.9637, -10.0094], requires_grad=True)
tensor(517.5957, grad_fn=<AddBackward0>)
tensor([ -9.8807,  -9.8091,  -9.8615,  -6.2494, -10.1941, -10.2049,  -9.9461,
         -6.3206,  -9.9650, -10.0107], requires_grad=True)
tensor(517.6608, grad_fn=<AddBackward0>)
tensor([ -9.8821,  -9.8105,  -9.8628,  -6.2504, -10.1954, -10.2062,  -9.9474,
         -6.3216,  -9.9663, -10.0120], requires_grad=True)
tensor(517.7261, grad_fn=<AddBackward0>)
tensor([ -9.8835,  -9.8119,  -9.8641,  -6.2514, -10.1967, -10.2075,  -9.9486,
         -6.3226,  -9.9676, -10.

tensor([-10.0834, -10.0125, -10.0512,  -6.3945, -10.3803, -10.3920, -10.1308,
         -6.4656, -10.1536, -10.1968], requires_grad=True)
tensor(527.0923, grad_fn=<AddBackward0>)
tensor([-10.0848, -10.0139, -10.0525,  -6.3955, -10.3815, -10.3933, -10.1321,
         -6.4666, -10.1549, -10.1981], requires_grad=True)
tensor(527.1573, grad_fn=<AddBackward0>)
tensor([-10.0862, -10.0153, -10.0539,  -6.3965, -10.3828, -10.3946, -10.1334,
         -6.4676, -10.1562, -10.1993], requires_grad=True)
tensor(527.2222, grad_fn=<AddBackward0>)
tensor([-10.0876, -10.0167, -10.0552,  -6.3975, -10.3841, -10.3959, -10.1347,
         -6.4686, -10.1574, -10.2006], requires_grad=True)
tensor(527.2871, grad_fn=<AddBackward0>)
tensor([-10.0890, -10.0181, -10.0565,  -6.3985, -10.3854, -10.3972, -10.1359,
         -6.4696, -10.1587, -10.2019], requires_grad=True)
tensor(527.3520, grad_fn=<AddBackward0>)
tensor([-10.0904, -10.0195, -10.0578,  -6.3995, -10.3867, -10.3985, -10.1372,
         -6.4706, -10.1600, -10.

tensor([-10.3040, -10.2337, -10.2582,  -6.5535, -10.5834, -10.5960, -10.3324,
         -6.6247, -10.3593, -10.3998], requires_grad=True)
tensor(537.3956, grad_fn=<AddBackward0>)
tensor([-10.3054, -10.2350, -10.2595,  -6.5545, -10.5846, -10.5973, -10.3336,
         -6.6257, -10.3606, -10.4011], requires_grad=True)
tensor(537.4603, grad_fn=<AddBackward0>)
tensor([-10.3067, -10.2364, -10.2608,  -6.5555, -10.5859, -10.5986, -10.3349,
         -6.6267, -10.3619, -10.4023], requires_grad=True)
tensor(537.5251, grad_fn=<AddBackward0>)
tensor([-10.3081, -10.2378, -10.2621,  -6.5565, -10.5872, -10.5999, -10.3362,
         -6.6277, -10.3632, -10.4036], requires_grad=True)
tensor(537.5897, grad_fn=<AddBackward0>)
tensor([-10.3095, -10.2392, -10.2634,  -6.5575, -10.5885, -10.6011, -10.3374,
         -6.6287, -10.3645, -10.4049], requires_grad=True)
tensor(537.6543, grad_fn=<AddBackward0>)
tensor([-10.3109, -10.2406, -10.2647,  -6.5585, -10.5897, -10.6024, -10.3387,
         -6.6297, -10.3658, -10.

tensor([-10.5366, -10.4665, -10.4769,  -6.7226, -10.7981, -10.8115, -10.5454,
         -6.7937, -10.5768, -10.6144], requires_grad=True)
tensor(548.3066, grad_fn=<AddBackward0>)
tensor([-10.5379, -10.4679, -10.4782,  -6.7236, -10.7994, -10.8128, -10.5467,
         -6.7947, -10.5781, -10.6157], requires_grad=True)
tensor(548.3710, grad_fn=<AddBackward0>)
tensor([-10.5393, -10.4693, -10.4795,  -6.7246, -10.8007, -10.8140, -10.5479,
         -6.7957, -10.5794, -10.6169], requires_grad=True)
tensor(548.4355, grad_fn=<AddBackward0>)
tensor([-10.5407, -10.4707, -10.4808,  -6.7256, -10.8019, -10.8153, -10.5492,
         -6.7967, -10.5807, -10.6182], requires_grad=True)
tensor(548.4999, grad_fn=<AddBackward0>)
tensor([-10.5421, -10.4720, -10.4821,  -6.7266, -10.8032, -10.8166, -10.5504,
         -6.7977, -10.5820, -10.6195], requires_grad=True)
tensor(548.5644, grad_fn=<AddBackward0>)
tensor([-10.5434, -10.4734, -10.4834,  -6.7276, -10.8045, -10.8179, -10.5517,
         -6.7987, -10.5832, -10.

         -6.9578, -10.7868, -10.8216], requires_grad=True)
tensor(558.8570, grad_fn=<AddBackward0>)
tensor([-10.7619, -10.6919, -10.6893,  -6.8877, -11.0067, -11.0206, -10.7523,
         -6.9588, -10.7881, -10.8229], requires_grad=True)
tensor(558.9213, grad_fn=<AddBackward0>)
tensor([-10.7633, -10.6933, -10.6906,  -6.8887, -11.0080, -11.0219, -10.7536,
         -6.9598, -10.7894, -10.8241], requires_grad=True)
tensor(558.9855, grad_fn=<AddBackward0>)
tensor([-10.7646, -10.6946, -10.6919,  -6.8897, -11.0093, -11.0231, -10.7548,
         -6.9608, -10.7906, -10.8254], requires_grad=True)
tensor(559.0498, grad_fn=<AddBackward0>)
tensor([-10.7660, -10.6960, -10.6932,  -6.8907, -11.0105, -11.0244, -10.7561,
         -6.9618, -10.7919, -10.8267], requires_grad=True)
tensor(559.1140, grad_fn=<AddBackward0>)
tensor([-10.7673, -10.6974, -10.6945,  -6.8917, -11.0118, -11.0257, -10.7573,
         -6.9628, -10.7932, -10.8279], requires_grad=True)
tensor(559.1782, grad_fn=<AddBackward0>)
tensor([-1

tensor([-10.9450, -10.8749, -10.8623,  -7.0227, -11.1767, -11.1909, -10.9208,
         -7.0939, -10.9602, -10.9927], requires_grad=True)
tensor(567.5801, grad_fn=<AddBackward0>)
tensor([-10.9464, -10.8763, -10.8636,  -7.0237, -11.1779, -11.1921, -10.9221,
         -7.0949, -10.9614, -10.9939], requires_grad=True)
tensor(567.6443, grad_fn=<AddBackward0>)
tensor([-10.9477, -10.8776, -10.8648,  -7.0247, -11.1792, -11.1934, -10.9233,
         -7.0959, -10.9627, -10.9952], requires_grad=True)
tensor(567.7083, grad_fn=<AddBackward0>)
tensor([-10.9491, -10.8790, -10.8661,  -7.0257, -11.1804, -11.1946, -10.9246,
         -7.0969, -10.9640, -10.9964], requires_grad=True)
tensor(567.7723, grad_fn=<AddBackward0>)
tensor([-10.9504, -10.8803, -10.8674,  -7.0267, -11.1817, -11.1959, -10.9258,
         -7.0979, -10.9652, -10.9977], requires_grad=True)
tensor(567.8364, grad_fn=<AddBackward0>)
tensor([-10.9518, -10.8817, -10.8687,  -7.0277, -11.1829, -11.1971, -10.9271,
         -7.0989, -10.9665, -10.

tensor([-11.1566, -11.0862, -11.0625,  -7.1797, -11.3735, -11.3879, -11.1160,
         -7.2509, -11.1594, -11.1893], requires_grad=True)
tensor(577.6226, grad_fn=<AddBackward0>)
tensor([-11.1579, -11.0876, -11.0638,  -7.1807, -11.3747, -11.3891, -11.1173,
         -7.2519, -11.1607, -11.1905], requires_grad=True)
tensor(577.6863, grad_fn=<AddBackward0>)
tensor([-11.1593, -11.0889, -11.0651,  -7.1817, -11.3760, -11.3904, -11.1185,
         -7.2529, -11.1620, -11.1918], requires_grad=True)
tensor(577.7504, grad_fn=<AddBackward0>)
tensor([-11.1606, -11.0902, -11.0663,  -7.1827, -11.3772, -11.3916, -11.1197,
         -7.2539, -11.1632, -11.1930], requires_grad=True)
tensor(577.8142, grad_fn=<AddBackward0>)
tensor([-11.1620, -11.0916, -11.0676,  -7.1837, -11.3785, -11.3929, -11.1210,
         -7.2549, -11.1645, -11.1943], requires_grad=True)
tensor(577.8781, grad_fn=<AddBackward0>)
tensor([-11.1633, -11.0929, -11.0689,  -7.1847, -11.3797, -11.3941, -11.1222,
         -7.2559, -11.1658, -11.

tensor([-11.3721, -11.3013, -11.2669,  -7.3407, -11.5744, -11.5889, -11.3153,
         -7.4119, -11.3628, -11.3901], requires_grad=True)
tensor(587.8918, grad_fn=<AddBackward0>)
tensor([-11.3735, -11.3027, -11.2682,  -7.3417, -11.5756, -11.5902, -11.3165,
         -7.4129, -11.3641, -11.3913], requires_grad=True)
tensor(587.9555, grad_fn=<AddBackward0>)
tensor([-11.3748, -11.3040, -11.2695,  -7.3427, -11.5769, -11.5914, -11.3177,
         -7.4139, -11.3654, -11.3925], requires_grad=True)
tensor(588.0192, grad_fn=<AddBackward0>)
tensor([-11.3761, -11.3053, -11.2707,  -7.3437, -11.5781, -11.5927, -11.3190,
         -7.4149, -11.3666, -11.3938], requires_grad=True)
tensor(588.0830, grad_fn=<AddBackward0>)
tensor([-11.3775, -11.3067, -11.2720,  -7.3447, -11.5794, -11.5939, -11.3202,
         -7.4159, -11.3679, -11.3950], requires_grad=True)
tensor(588.1467, grad_fn=<AddBackward0>)
tensor([-11.3788, -11.3080, -11.2733,  -7.3457, -11.5806, -11.5952, -11.3215,
         -7.4169, -11.3691, -11.

tensor(596.9897, grad_fn=<AddBackward0>)
tensor([-11.5637, -11.4925, -11.4489,  -7.4847, -11.7534, -11.7680, -11.4928,
         -7.5559, -11.5440, -11.5689], requires_grad=True)
tensor(597.0533, grad_fn=<AddBackward0>)
tensor([-11.5651, -11.4938, -11.4502,  -7.4857, -11.7546, -11.7692, -11.4940,
         -7.5569, -11.5453, -11.5701], requires_grad=True)
tensor(597.1168, grad_fn=<AddBackward0>)
tensor([-11.5664, -11.4951, -11.4515,  -7.4867, -11.7559, -11.7704, -11.4952,
         -7.5579, -11.5465, -11.5714], requires_grad=True)
tensor(597.1804, grad_fn=<AddBackward0>)
tensor([-11.5677, -11.4964, -11.4527,  -7.4877, -11.7571, -11.7717, -11.4965,
         -7.5589, -11.5478, -11.5726], requires_grad=True)
tensor(597.2440, grad_fn=<AddBackward0>)
tensor([-11.5690, -11.4978, -11.4540,  -7.4887, -11.7584, -11.7729, -11.4977,
         -7.5599, -11.5491, -11.5738], requires_grad=True)
tensor(597.3075, grad_fn=<AddBackward0>)
tensor([-11.5704, -11.4991, -11.4552,  -7.4897, -11.7596, -11.7742, -

tensor(604.1643, grad_fn=<AddBackward0>)
tensor([-11.7133, -11.6416, -11.5913,  -7.5977, -11.8934, -11.9079, -11.6316,
         -7.6689, -11.6857, -11.7088], requires_grad=True)
tensor(604.2277, grad_fn=<AddBackward0>)
tensor([-11.7147, -11.6429, -11.5925,  -7.5987, -11.8946, -11.9092, -11.6328,
         -7.6699, -11.6870, -11.7100], requires_grad=True)
tensor(604.2912, grad_fn=<AddBackward0>)
tensor([-11.7160, -11.6443, -11.5938,  -7.5997, -11.8959, -11.9104, -11.6341,
         -7.6709, -11.6882, -11.7112], requires_grad=True)
tensor(604.3546, grad_fn=<AddBackward0>)
tensor([-11.7173, -11.6456, -11.5950,  -7.6007, -11.8971, -11.9116, -11.6353,
         -7.6719, -11.6895, -11.7125], requires_grad=True)
tensor(604.4182, grad_fn=<AddBackward0>)
tensor([-11.7186, -11.6469, -11.5963,  -7.6017, -11.8983, -11.9129, -11.6365,
         -7.6729, -11.6907, -11.7137], requires_grad=True)
tensor(604.4816, grad_fn=<AddBackward0>)
tensor([-11.7199, -11.6482, -11.5976,  -7.6027, -11.8996, -11.9141, -

         -7.8288, -11.8857, -11.9061], requires_grad=True)
tensor(614.3652, grad_fn=<AddBackward0>)
tensor([-11.9254, -11.8530, -11.7933,  -7.7587, -12.0922, -12.1066, -11.8288,
         -7.8298, -11.8869, -11.9074], requires_grad=True)
tensor(614.4285, grad_fn=<AddBackward0>)
tensor([-11.9267, -11.8543, -11.7946,  -7.7597, -12.0934, -12.1078, -11.8300,
         -7.8308, -11.8882, -11.9086], requires_grad=True)
tensor(614.4918, grad_fn=<AddBackward0>)
tensor([-11.9280, -11.8556, -11.7958,  -7.7607, -12.0947, -12.1091, -11.8312,
         -7.8318, -11.8894, -11.9098], requires_grad=True)
tensor(614.5552, grad_fn=<AddBackward0>)
tensor([-11.9293, -11.8569, -11.7971,  -7.7617, -12.0959, -12.1103, -11.8324,
         -7.8328, -11.8907, -11.9111], requires_grad=True)
tensor(614.6184, grad_fn=<AddBackward0>)
tensor([-11.9306, -11.8582, -11.7983,  -7.7627, -12.0971, -12.1115, -11.8337,
         -7.8338, -11.8919, -11.9123], requires_grad=True)
tensor(614.6816, grad_fn=<AddBackward0>)
tensor([-1

tensor([-12.0695, -11.9966, -11.9309,  -7.8687, -12.2276, -12.2418, -11.9630,
         -7.9398, -12.0239, -12.0426], requires_grad=True)
tensor(621.3842, grad_fn=<AddBackward0>)
tensor([-12.0708, -11.9979, -11.9321,  -7.8697, -12.2288, -12.2431, -11.9642,
         -7.9408, -12.0251, -12.0438], requires_grad=True)
tensor(621.4473, grad_fn=<AddBackward0>)
tensor([-12.0721, -11.9992, -11.9334,  -7.8707, -12.2301, -12.2443, -11.9655,
         -7.9418, -12.0264, -12.0451], requires_grad=True)
tensor(621.5104, grad_fn=<AddBackward0>)
tensor([-12.0734, -12.0005, -11.9346,  -7.8717, -12.2313, -12.2455, -11.9667,
         -7.9428, -12.0276, -12.0463], requires_grad=True)
tensor(621.5736, grad_fn=<AddBackward0>)
tensor([-12.0748, -12.0018, -11.9359,  -7.8727, -12.2325, -12.2467, -11.9679,
         -7.9438, -12.0289, -12.0475], requires_grad=True)
tensor(621.6368, grad_fn=<AddBackward0>)
tensor([-12.0761, -12.0031, -11.9371,  -7.8737, -12.2337, -12.2480, -11.9691,
         -7.9448, -12.0301, -12.

tensor([-12.2392, -12.1656, -12.0929,  -7.9987, -12.3872, -12.4012, -12.1213,
         -8.0699, -12.1853, -12.2020], requires_grad=True)
tensor(629.5908, grad_fn=<AddBackward0>)
tensor([-12.2405, -12.1669, -12.0942,  -7.9997, -12.3884, -12.4024, -12.1225,
         -8.0709, -12.1866, -12.2032], requires_grad=True)
tensor(629.6539, grad_fn=<AddBackward0>)
tensor([-12.2418, -12.1682, -12.0954,  -8.0007, -12.3896, -12.4036, -12.1237,
         -8.0719, -12.1878, -12.2045], requires_grad=True)
tensor(629.7170, grad_fn=<AddBackward0>)
tensor([-12.2431, -12.1695, -12.0967,  -8.0017, -12.3908, -12.4049, -12.1249,
         -8.0729, -12.1890, -12.2057], requires_grad=True)
tensor(629.7800, grad_fn=<AddBackward0>)
tensor([-12.2444, -12.1708, -12.0979,  -8.0027, -12.3921, -12.4061, -12.1261,
         -8.0739, -12.1903, -12.2069], requires_grad=True)
tensor(629.8430, grad_fn=<AddBackward0>)
tensor([-12.2457, -12.1721, -12.0992,  -8.0037, -12.3933, -12.4073, -12.1273,
         -8.0749, -12.1915, -12.

tensor([-12.4534, -12.3789, -12.2979,  -8.1637, -12.5890, -12.6027, -12.3214,
         -8.2349, -12.3895, -12.4037], requires_grad=True)
tensor(639.9871, grad_fn=<AddBackward0>)
tensor([-12.4547, -12.3802, -12.2991,  -8.1647, -12.5902, -12.6039, -12.3226,
         -8.2359, -12.3907, -12.4049], requires_grad=True)
tensor(640.0499, grad_fn=<AddBackward0>)
tensor([-12.4560, -12.3815, -12.3004,  -8.1657, -12.5915, -12.6051, -12.3239,
         -8.2369, -12.3919, -12.4061], requires_grad=True)
tensor(640.1129, grad_fn=<AddBackward0>)
tensor([-12.4573, -12.3828, -12.3016,  -8.1667, -12.5927, -12.6064, -12.3251,
         -8.2379, -12.3932, -12.4073], requires_grad=True)
tensor(640.1759, grad_fn=<AddBackward0>)
tensor([-12.4585, -12.3841, -12.3029,  -8.1677, -12.5939, -12.6076, -12.3263,
         -8.2389, -12.3944, -12.4085], requires_grad=True)
tensor(640.2388, grad_fn=<AddBackward0>)
tensor([-12.4598, -12.3854, -12.3041,  -8.1687, -12.5951, -12.6088, -12.3275,
         -8.2399, -12.3957, -12.

tensor([-12.6381, -12.5628, -12.4749,  -8.3068, -12.7634, -12.7767, -12.4943,
         -8.3780, -12.5658, -12.5778], requires_grad=True)
tensor(648.9788, grad_fn=<AddBackward0>)
tensor([-12.6394, -12.5641, -12.4761,  -8.3078, -12.7646, -12.7779, -12.4956,
         -8.3790, -12.5670, -12.5790], requires_grad=True)
tensor(649.0416, grad_fn=<AddBackward0>)
tensor([-12.6406, -12.5654, -12.4774,  -8.3088, -12.7658, -12.7791, -12.4968,
         -8.3800, -12.5683, -12.5803], requires_grad=True)
tensor(649.1044, grad_fn=<AddBackward0>)
tensor([-12.6419, -12.5666, -12.4786,  -8.3098, -12.7670, -12.7804, -12.4980,
         -8.3810, -12.5695, -12.5815], requires_grad=True)
tensor(649.1672, grad_fn=<AddBackward0>)
tensor([-12.6432, -12.5679, -12.4798,  -8.3108, -12.7683, -12.7816, -12.4992,
         -8.3820, -12.5707, -12.5827], requires_grad=True)
tensor(649.2301, grad_fn=<AddBackward0>)
tensor([-12.6445, -12.5692, -12.4811,  -8.3118, -12.7695, -12.7828, -12.5004,
         -8.3830, -12.5720, -12.

tensor([-12.8527, -12.7764, -12.6808,  -8.4739, -12.9663, -12.9792, -12.6956,
         -8.5451, -12.7710, -12.7806], requires_grad=True)
tensor(659.4604, grad_fn=<AddBackward0>)
tensor([-12.8540, -12.7777, -12.6821,  -8.4749, -12.9675, -12.9804, -12.6968,
         -8.5461, -12.7722, -12.7818], requires_grad=True)
tensor(659.5231, grad_fn=<AddBackward0>)
tensor([-12.8553, -12.7790, -12.6833,  -8.4759, -12.9688, -12.9816, -12.6980,
         -8.5471, -12.7735, -12.7830], requires_grad=True)
tensor(659.5859, grad_fn=<AddBackward0>)
tensor([-12.8565, -12.7803, -12.6845,  -8.4769, -12.9700, -12.9828, -12.6992,
         -8.5481, -12.7747, -12.7842], requires_grad=True)
tensor(659.6486, grad_fn=<AddBackward0>)
tensor([-12.8578, -12.7816, -12.6858,  -8.4779, -12.9712, -12.9841, -12.7004,
         -8.5491, -12.7759, -12.7854], requires_grad=True)
tensor(659.7113, grad_fn=<AddBackward0>)
tensor([-12.8591, -12.7828, -12.6870,  -8.4789, -12.9724, -12.9853, -12.7017,
         -8.5501, -12.7771, -12.

tensor(669.6716, grad_fn=<AddBackward0>)
tensor([-13.0624, -12.9851, -12.8824,  -8.6379, -13.1650, -13.1774, -12.8927,
         -8.7091, -12.9718, -12.9790], requires_grad=True)
tensor(669.7343, grad_fn=<AddBackward0>)
tensor([-13.0637, -12.9864, -12.8836,  -8.6389, -13.1662, -13.1786, -12.8939,
         -8.7101, -12.9730, -12.9802], requires_grad=True)
tensor(669.7969, grad_fn=<AddBackward0>)
tensor([-13.0649, -12.9877, -12.8848,  -8.6399, -13.1674, -13.1798, -12.8951,
         -8.7111, -12.9743, -12.9814], requires_grad=True)
tensor(669.8594, grad_fn=<AddBackward0>)
tensor([-13.0662, -12.9889, -12.8860,  -8.6409, -13.1686, -13.1810, -12.8963,
         -8.7121, -12.9755, -12.9826], requires_grad=True)
tensor(669.9220, grad_fn=<AddBackward0>)
tensor([-13.0675, -12.9902, -12.8873,  -8.6419, -13.1698, -13.1822, -12.8975,
         -8.7131, -12.9767, -12.9838], requires_grad=True)
tensor(669.9847, grad_fn=<AddBackward0>)
tensor([-13.0688, -12.9915, -12.8885,  -8.6429, -13.1710, -13.1834, -

tensor(676.8636, grad_fn=<AddBackward0>)
tensor([-13.2088, -13.1309, -13.0232,  -8.7530, -13.3039, -13.3159, -13.0304,
         -8.8242, -13.1122, -13.1177], requires_grad=True)
tensor(676.9260, grad_fn=<AddBackward0>)
tensor([-13.2101, -13.1321, -13.0245,  -8.7540, -13.3051, -13.3171, -13.0316,
         -8.8252, -13.1134, -13.1189], requires_grad=True)
tensor(676.9885, grad_fn=<AddBackward0>)
tensor([-13.2114, -13.1334, -13.0257,  -8.7550, -13.3063, -13.3183, -13.0328,
         -8.8262, -13.1146, -13.1201], requires_grad=True)
tensor(677.0510, grad_fn=<AddBackward0>)
tensor([-13.2126, -13.1346, -13.0269,  -8.7560, -13.3075, -13.3195, -13.0340,
         -8.8272, -13.1159, -13.1214], requires_grad=True)
tensor(677.1135, grad_fn=<AddBackward0>)
tensor([-13.2139, -13.1359, -13.0281,  -8.7570, -13.3087, -13.3207, -13.0352,
         -8.8282, -13.1171, -13.1226], requires_grad=True)
tensor(677.1760, grad_fn=<AddBackward0>)
tensor([-13.2152, -13.1372, -13.0293,  -8.7580, -13.3099, -13.3219, -

tensor([-13.4105, -13.3315, -13.2174,  -8.9120, -13.4954, -13.5069, -13.2205,
         -8.9832, -13.3058, -13.3091], requires_grad=True)
tensor(686.8564, grad_fn=<AddBackward0>)
tensor([-13.4117, -13.3327, -13.2187,  -8.9130, -13.4966, -13.5081, -13.2216,
         -8.9842, -13.3070, -13.3103], requires_grad=True)
tensor(686.9188, grad_fn=<AddBackward0>)
tensor([-13.4130, -13.3340, -13.2199,  -8.9140, -13.4978, -13.5093, -13.2228,
         -8.9852, -13.3082, -13.3115], requires_grad=True)
tensor(686.9811, grad_fn=<AddBackward0>)
tensor([-13.4143, -13.3353, -13.2211,  -8.9150, -13.4991, -13.5105, -13.2240,
         -8.9862, -13.3094, -13.3127], requires_grad=True)
tensor(687.0435, grad_fn=<AddBackward0>)
tensor([-13.4155, -13.3365, -13.2223,  -8.9160, -13.5003, -13.5117, -13.2252,
         -8.9872, -13.3106, -13.3139], requires_grad=True)
tensor(687.1060, grad_fn=<AddBackward0>)
tensor([-13.4168, -13.3378, -13.2235,  -8.9171, -13.5015, -13.5129, -13.2264,
         -8.9882, -13.3119, -13.

tensor([-13.6200, -13.5400, -13.4195,  -9.0781, -13.6948, -13.7057, -13.4183,
         -9.1493, -13.5072, -13.5082], requires_grad=True)
tensor(697.2067, grad_fn=<AddBackward0>)
tensor([-13.6213, -13.5412, -13.4208,  -9.0791, -13.6960, -13.7068, -13.4194,
         -9.1503, -13.5084, -13.5094], requires_grad=True)
tensor(697.2689, grad_fn=<AddBackward0>)
tensor([-13.6226, -13.5425, -13.4220,  -9.0801, -13.6972, -13.7080, -13.4206,
         -9.1513, -13.5097, -13.5106], requires_grad=True)
tensor(697.3312, grad_fn=<AddBackward0>)
tensor([-13.6238, -13.5437, -13.4232,  -9.0811, -13.6984, -13.7092, -13.4218,
         -9.1523, -13.5109, -13.5118], requires_grad=True)
tensor(697.3935, grad_fn=<AddBackward0>)
tensor([-13.6251, -13.5450, -13.4244,  -9.0821, -13.6996, -13.7104, -13.4230,
         -9.1533, -13.5121, -13.5130], requires_grad=True)
tensor(697.4557, grad_fn=<AddBackward0>)
tensor([-13.6263, -13.5463, -13.4256,  -9.0831, -13.7008, -13.7116, -13.4242,
         -9.1543, -13.5133, -13.

tensor([-13.8337, -13.7525, -13.6258,  -9.2482, -13.8984, -13.9086, -13.6202,
         -9.3194, -13.7129, -13.7116], requires_grad=True)
tensor(707.7886, grad_fn=<AddBackward0>)
tensor([-13.8349, -13.7538, -13.6270,  -9.2492, -13.8996, -13.9098, -13.6214,
         -9.3204, -13.7141, -13.7128], requires_grad=True)
tensor(707.8507, grad_fn=<AddBackward0>)
tensor([-13.8362, -13.7550, -13.6282,  -9.2502, -13.9008, -13.9109, -13.6226,
         -9.3214, -13.7153, -13.7140], requires_grad=True)
tensor(707.9128, grad_fn=<AddBackward0>)
tensor([-13.8374, -13.7563, -13.6295,  -9.2512, -13.9020, -13.9121, -13.6238,
         -9.3224, -13.7165, -13.7152], requires_grad=True)
tensor(707.9750, grad_fn=<AddBackward0>)
tensor([-13.8387, -13.7575, -13.6307,  -9.2522, -13.9032, -13.9133, -13.6250,
         -9.3234, -13.7177, -13.7164], requires_grad=True)
tensor(708.0371, grad_fn=<AddBackward0>)
tensor([-13.8400, -13.7588, -13.6319,  -9.2532, -13.9044, -13.9145, -13.6262,
         -9.3244, -13.7189, -13.

tensor(717.3596, grad_fn=<AddBackward0>)
tensor([-14.0277, -13.9455, -13.8133,  -9.4032, -14.0835, -14.0930, -13.8039,
         -9.4744, -13.8998, -13.8965], requires_grad=True)
tensor(717.4216, grad_fn=<AddBackward0>)
tensor([-14.0289, -13.9467, -13.8145,  -9.4042, -14.0847, -14.0942, -13.8051,
         -9.4754, -13.9010, -13.8977], requires_grad=True)
tensor(717.4838, grad_fn=<AddBackward0>)
tensor([-14.0302, -13.9480, -13.8157,  -9.4052, -14.0859, -14.0954, -13.8062,
         -9.4764, -13.9022, -13.8989], requires_grad=True)
tensor(717.5458, grad_fn=<AddBackward0>)
tensor([-14.0314, -13.9492, -13.8169,  -9.4062, -14.0871, -14.0966, -13.8074,
         -9.4774, -13.9034, -13.9001], requires_grad=True)
tensor(717.6078, grad_fn=<AddBackward0>)
tensor([-14.0327, -13.9504, -13.8181,  -9.4072, -14.0883, -14.0978, -13.8086,
         -9.4784, -13.9046, -13.9013], requires_grad=True)
tensor(717.6699, grad_fn=<AddBackward0>)
tensor([-14.0339, -13.9517, -13.8194,  -9.4082, -14.0895, -14.0990, -

In [33]:
model = nn.Linear(10, 2)
temp_weights=[w.clone() for w in list(model.parameters())]

weights = torch.ones(10, requires_grad=True)

criterion = nn.CrossEntropyLoss()
meta_opt = optim.Adam(model.parameters())

target = torch.empty(1, dtype=torch.long).random_(2)

alpha = 0.001

x = torch.randn(1, 10)

for e in range(100):
    # inner loop optimize the model weights
    meta_loss = 0
    
    for _ in range(10):
        
        output = F.linear(x,temp_weights[0],temp_weights[1])
        loss = criterion(output, target)
        w_loss = (loss * weights).sum() / weights.sum()

        grads = torch.autograd.grad(w_loss,temp_weights)
        temp_weights = [w-alpha*g for w,g in zip(temp_weights,grads)] #temporary update of weights
        output = F.linear(x,temp_weights[0],temp_weights[1])
        meta_loss += criterion(output,target)
        #meta_loss = (loss * weights).sum() / weights.sum()
    print(criterion(output,target))
    
    metagrads=torch.autograd.grad(meta_loss, model.parameters())
    for w,g in zip(model.parameters(),metagrads):
        w.grad=g
        
    meta_opt.step()


#

tensor(0.1648, grad_fn=<NllLossBackward>)
tensor(0.1553, grad_fn=<NllLossBackward>)
tensor(0.1468, grad_fn=<NllLossBackward>)
tensor(0.1391, grad_fn=<NllLossBackward>)
tensor(0.1321, grad_fn=<NllLossBackward>)
tensor(0.1258, grad_fn=<NllLossBackward>)
tensor(0.1200, grad_fn=<NllLossBackward>)
tensor(0.1147, grad_fn=<NllLossBackward>)
tensor(0.1098, grad_fn=<NllLossBackward>)
tensor(0.1053, grad_fn=<NllLossBackward>)
tensor(0.1011, grad_fn=<NllLossBackward>)
tensor(0.0972, grad_fn=<NllLossBackward>)
tensor(0.0936, grad_fn=<NllLossBackward>)
tensor(0.0903, grad_fn=<NllLossBackward>)
tensor(0.0872, grad_fn=<NllLossBackward>)
tensor(0.0843, grad_fn=<NllLossBackward>)
tensor(0.0815, grad_fn=<NllLossBackward>)
tensor(0.0789, grad_fn=<NllLossBackward>)
tensor(0.0765, grad_fn=<NllLossBackward>)
tensor(0.0742, grad_fn=<NllLossBackward>)
tensor(0.0721, grad_fn=<NllLossBackward>)
tensor(0.0700, grad_fn=<NllLossBackward>)
tensor(0.0681, grad_fn=<NllLossBackward>)
tensor(0.0663, grad_fn=<NllLossBac